### ISSUE TITLE
Limit the number of characters for the comment field

### ISSUE THREAD

**Issue by ZiRo-** [majestrate/srndv2#10]
Posting [this](https://www.gutenberg.org/ebooks/10) for example locks the whole thing up for a few seconds.

**Comment by majestrate** [comment]
Posting large text should be limited already but the checks in place are done later in the code than they should, probably.

**Comment by ZiRo-** [comment]
You're right.
But as you can see here:
https://github.com/majestrate/srndv2/blob/c97c4fe3825bb551c54f15892ec69c87522e2007/src/srnd/frontend_http.go#L588
If no files are attached the check is skipped.

**Comment by majestrate** [comment]
good find

**Comment by majestrate** [comment]
try https://github.com/majestrate/srndv2/commit/09c8a12d3f8caea5f678525bffb6a2cf9bc82b9c

**Comment by ZiRo-** [comment]
Also ~10 MB for a comment field is an insanely high default.
10 KB should be more than enough.

**Comment by ZiRo-** [comment]
Oh, and you probably want to have these checks for the name and subject field too.

**Comment by majestrate** [comment]
yes

**Comment by majestrate** [comment]
https://github.com/majestrate/srndv2/commit/55b7782835ddf005e43b7cc9a793632a755f41a4 fixes added in mixed with go fmt, i think the git hooks i use for go aren't in place otherwise go fmt would be called automatically.
