### ISSUE TITLE
Recache the board model when a new thread is created

### ISSUE THREAD

**Issue by ZiRo-** [majestrate/srndv2#11]
When a new thread is created it potentially creates a new page, but currently this results in this error:
`board page should not exist`
because the new page isn't added to the board model.

**Comment by majestrate** [comment]
sounds like a race condition (maybe?), there are 2 different workers for regenerating pages, one for threads and 1 for board pages. Sounds like this would happen if the thread regeneration was done before the board pages.

**Comment by majestrate** [comment]
try https://github.com/majestrate/srndv2/commit/9023924ac3b8797d471a908205d6889ff775ba2e

**Comment by ZiRo-** [comment]
This does fix the issue, I think.
But it creates another one where the new thread isn't detected:
`we didn't find thread for ... did not regenerate`
Which probably is a race condition in this case.

**Comment by ZiRo-** [comment]
I tried a few things, if you roll back your changes to model.go it works perfectly fine.

**Comment by majestrate** [comment]
which revision specifically?
