### ISSUE TITLE
>>fffffffff  ImageBoard links for NNTP transfer.

### ISSUE THREAD

**Issue by Anoncheg1** [majestrate/srndv2#35]
Hello. I am working at diploma about your nntpchan. It is Java implementation.

We have problem with links in messages, like this:
`>>fc346a235`
We need NNTP format for links => convertation from your local 
articles:message_id_hash ... to ... global message-id of NNTP.
When you feed(peering) with NNTP.

I will public my full work when it will be completed. See you.

**Comment by Anoncheg1** [comment]
I don't knew how to do it now. Let's think about it.

**Comment by majestrate** [comment]
I like the >>blahblah@something.tld style links idea. A problem I see with the >>1 >>2 style is that not all messages will propagate fully so the order will be not be sequential.

**Comment by Anoncheg1** [comment]
Let's add
>>blahblah@something.tld
links style to NNTP protocol recommendation.

**Comment by majestrate** [comment]
if >>local does not match to an existing message it should probably not be rewritten

can you elaborate on what >>local is? do you mean >>1 >>2 >>3 etc?

**Comment by Anoncheg1** [comment]
`>>local` - short link in certain server.
links in NNTP message body. - global `<asdasdasd@serv.org>` links

**Comment by majestrate** [comment]
How would this work with signed posts?

**Comment by Anoncheg1** [comment]
I think
>>asdasdasd@serv.orgSPACE
is good format for in-body links.

**Comment by majestrate** [comment]
so given <messageid@server.tld> the back link would be
>>messageid@server.tld ?

**Comment by majestrate** [comment]
\>>messageid@server.tld
