### ISSUE TITLE
auto reload daemon on runtime after recompiling

### ISSUE THREAD

**Issue by majestrate** [majestrate/srndv2#36]
Whenever I update i have to stop the daemon, git pull and recompile, the process is unacceptably too long.

I think we need a way to reload the daemon live via signal, i.e. SIGUSR1

Can't touch the running binary executable so this would require a wrapper program that loads/unloads a shared library module ? Some other way?

**Comment by ZiRo-** [comment]
I don't know about you, but when I update binaries (nginx for example) I do it the following way:

-pull source
-build
-systemctl stop
-install
-systemctl start

This keeps the downtime to a minimum.
If you don't want any downtime at all you'd need something like [this](https://www.digitalocean.com/community/tutorials/how-to-upgrade-nginx-in-place-without-dropping-client-connections).

**Comment by majestrate** [comment]
do you have the initscripts handy?

**Comment by ZiRo-** [comment]
I have user called nntp with the nntpchan directory in this user's home directory.
Then I have the following file in `/etc/systemd/system/srndv2.service`:
```
[Unit]
Description=srndv2
After=redis-server.service
Wants=redis-server.service

[Service]
User=nntp
ExecStart=/home/nntp/nntpchan/srndv2 run
WorkingDirectory=/home/nntp/nntpchan
Restart=on-failure

[Install]
WantedBy=default.target
```

And then I use the following modified build script to update:

```
set -e
root=$(readlink -e $(dirname $0))
cd $root
GOPATH=$root/go
sudo -E -u nntp go get -u github.com/majestrate/srndv2
sudo systemctl stop srndv2.service 
sudo -E -u nntp cp -a $GOPATH/bin/srndv2 $root
sudo systemctl  start srndv2.service
```

A bit of a hack with the sudo stuff, but it works. On Debian at least.

**Comment by majestrate** [comment]
probably can do this with initscripts
