### ISSUE TITLE
UTF-8 and Subject: - header of article. NNTP

### ISSUE THREAD

**Issue by Anoncheg1** [majestrate/srndv2#41]
Here is RFC 3977:

>    o  Header values SHOULD use US-ASCII or an encoding based on it, such
>       as RFC 2047 [RFC2047], until such time as another approach has
>       been standardised.  At present, 8-bit encodings (including UTF-8)
>       SHOULD NOT be used because they are likely to cause
>       interoperability problems

UTF-8 SHOULD NOT be used without "       =?utf-8?q?this is some text?=
But, This specification extends NNTP from US-ASCII to UTF-8.

Should we use =?utf-8?q??=

**Comment by majestrate** [comment]
we use UTF-8 regardless since it's $CURRENT_YEAR and not $CURRENT_YEAR - 1

**Comment by Anoncheg1** [comment]
What do you mean? We must follow RFC.
