### ISSUE TITLE
Web API Problems

### ISSUE THREAD

**Issue by odilitime** [majestrate/srndv2#43]
through nntp, I see this does exist
http://nsfl.tk/api/header?name=X-Mongo-ID&value=57260140c984bafa4cd5499e
but web api is returning []

**Comment by majestrate** [comment]
case sensitive, does the article have that an entry in the mime header `X-Mongo-ID: 57260140c984bafa4cd5499e`

**Comment by odilitime** [comment]
Yup, same case

**Comment by majestrate** [comment]
what database are you using for the daemon?

**Comment by odilitime** [comment]
(PostgreSQL) 9.3.11

**Comment by majestrate** [comment]
i pushed some changes in https://github.com/majestrate/srndv2/commit/f0f8dc486ca160ec7b3a4b3ce53ade279ff05989 that probably will fix this issue.

**Comment by majestrate** [comment]
let me know.
