### ISSUE TITLE
Potential rounding issues

### ISSUE THREAD

**Issue by ZiRo-** [majestrate/srndv2#5]
In the postgres driver there are several instances of 
`page / int64(perpage)`
which are converted to int again. This may lead to problems with floating point precision.
This is especially true for 
`( count / 10 ) + 1`
Let's say you have exactly 10 threads here, so with this code you may end up with the unexpected result of 2 pages.

The correct way to handle this, would be to use math.Ceil

**Comment by majestrate** [comment]
That would explain the page 10 problem

**Comment by majestrate** [comment]
https://github.com/majestrate/srndv2/commit/e501a40b3fb8b41aa54101648cd59bffb318535b should've fixed it
