### ISSUE TITLE
Do ping pong!

### ISSUE THREAD

**Issue by Anoncheg1** [majestrate/srndv2#53]
Send "500\n" or "говно\n" to maintain stream connection once in 1-2 min. Make it neatly. Do not send it in the middle of another transfer.

**Comment by majestrate** [comment]
what about sending `CHECK <no@op>\n` instead? that way no changes to protocol are needed.

**Comment by Anoncheg1** [comment]
Send "CHECK\r\n" without anything, be kind.
"501 invalid command usage" is response of mine.

**Comment by majestrate** [comment]
On Sat, Apr 22, 2017 at 02:26:37AM -0700, Anoncheg1 wrote:
> Send "CHECK\r\n" without anything, be kind.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/majestrate/srndv2/issues/53#issuecomment-296360706

CHECK with no arguments is not valid syntax, i'll just send a dummy CHECK.

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/nntpchan/commit/66655b18d5cba525263fa1e8b5ad3f493bb98f13
