### ISSUE TITLE
NNTP attachment Content-Disposition header.

### ISSUE THREAD

**Issue by Anoncheg1** [majestrate/srndv2#54]
You have broke something in new commits 
with Content-Disposition recognition.
I have such:
Content-Disposition: attachment; filename="name.png"

You can't display thumbnail.
Look at test board.

**Comment by majestrate** [comment]
Apr 29 16:08:33 anonet srndv2[19291]: 2017/04/29 16:08:33 error generating thumbnail convert: 
    Expected 4 bytes; found 3 bytes `webroot/img/7E65T23A5JFGOT4D5KNCXC2KSPZ2YQPJ2HQXWLNWTB4TS53WXPOLGMHFLNXFZ6Z7IS37ZEEYKRNKJHRKVG45GXGIM55FQLOUQ7OCB5Q=.png' @ warning/png.c/MagickPNGWarningHandler/1671

**Comment by majestrate** [comment]
looks like thumbnailer doesn't think it's a PNG

**Comment by Anoncheg1** [comment]
My fail with base64.
